# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InstanceDetectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/inference.InstanceDetector/Predict',
                request_serializer=inference__pb2.PredictRequest.SerializeToString,
                response_deserializer=inference__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.PredictWithConfidence = channel.unary_unary(
                '/inference.InstanceDetector/PredictWithConfidence',
                request_serializer=inference__pb2.PredictRequest.SerializeToString,
                response_deserializer=inference__pb2.PredictWithConfidenceResponse.FromString,
                _registered_method=True)
        self.BatchPredict = channel.unary_unary(
                '/inference.InstanceDetector/BatchPredict',
                request_serializer=inference__pb2.BatchPredictRequest.SerializeToString,
                response_deserializer=inference__pb2.BatchPredictResponse.FromString,
                _registered_method=True)
        self.PredictWithOptions = channel.unary_unary(
                '/inference.InstanceDetector/PredictWithOptions',
                request_serializer=inference__pb2.PredictWithOptionsRequest.SerializeToString,
                response_deserializer=inference__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/inference.InstanceDetector/GetModelInfo',
                request_serializer=inference__pb2.Empty.SerializeToString,
                response_deserializer=inference__pb2.ModelInfo.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/inference.InstanceDetector/HealthCheck',
                request_serializer=inference__pb2.Empty.SerializeToString,
                response_deserializer=inference__pb2.HealthResponse.FromString,
                _registered_method=True)


class InstanceDetectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictWithConfidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchPredict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictWithOptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InstanceDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=inference__pb2.PredictRequest.FromString,
                    response_serializer=inference__pb2.PredictResponse.SerializeToString,
            ),
            'PredictWithConfidence': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictWithConfidence,
                    request_deserializer=inference__pb2.PredictRequest.FromString,
                    response_serializer=inference__pb2.PredictWithConfidenceResponse.SerializeToString,
            ),
            'BatchPredict': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchPredict,
                    request_deserializer=inference__pb2.BatchPredictRequest.FromString,
                    response_serializer=inference__pb2.BatchPredictResponse.SerializeToString,
            ),
            'PredictWithOptions': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictWithOptions,
                    request_deserializer=inference__pb2.PredictWithOptionsRequest.FromString,
                    response_serializer=inference__pb2.PredictResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=inference__pb2.Empty.FromString,
                    response_serializer=inference__pb2.ModelInfo.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=inference__pb2.Empty.FromString,
                    response_serializer=inference__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.InstanceDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InstanceDetector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request,
                target,
                '/inference.InstanceDetector/Predict',
                inference__pb2.PredictRequest.SerializeToString,
                inference__pb2.PredictResponse.FromString,
                options, channel_credentials,
                insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PredictWithConfidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request,
                target,
                '/inference.InstanceDetector/PredictWithConfidence',
                inference__pb2.PredictRequest.SerializeToString,
                inference__pb2.PredictWithConfidenceResponse.FromString,
                options, channel_credentials,
                insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchPredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request,
                target,
                '/inference.InstanceDetector/BatchPredict',
                inference__pb2.BatchPredictRequest.SerializeToString,
                inference__pb2.BatchPredictResponse.FromString,
                options, channel_credentials,
                insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PredictWithOptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request,
                target,
                '/inference.InstanceDetector/PredictWithOptions',
                inference__pb2.PredictWithOptionsRequest.SerializeToString,
                inference__pb2.PredictResponse.FromString,
                options, channel_credentials,
                insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request,
                target,
                '/inference.InstanceDetector/GetModelInfo',
                inference__pb2.Empty.SerializeToString,
                inference__pb2.ModelInfo.FromString,
                options, channel_credentials,
                insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request,
                target,
                '/inference.InstanceDetector/HealthCheck',
                inference__pb2.Empty.SerializeToString,
                inference__pb2.HealthResponse.FromString,
                options, channel_credentials,
                insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
